import { BookOpen, CheckCircle2, CircleDot, ShieldCheck } from "lucide-react";
import type { AgentRun } from "../types";
import { Badge, SectionHeader } from "./ui";
import { RagPanel } from "./RagPanel";
import { TraceStageTimeline, buildTraceStages } from "./TraceTimeline";

export function GroundingPanel({ run }: { run: AgentRun }) {
  const stages = buildTraceStages(run).filter((stage) => ["intent", "context", "rag", "grounding", "target"].includes(stage.id));
  return <div className="space-y-5">
    <div className="grounding-boundary"><div className="grounding-column grounding-model"><div className="eyebrow text-proposal">Model proposal</div><div className="mt-2 text-sm font-semibold text-main">{run.intent || "Intent not recorded"}</div><div className="mt-1 text-xs leading-5 text-muted">Parsed intent and request type are observed model/runtime output, not execution authority.</div><div className="mt-3 flex flex-wrap gap-2"><span className="proposal-badge">untrusted proposal</span><Badge tone="neutral">{run.request_type.replace(/_/g, " ")}</Badge></div></div><div className="grounding-divider"><span>→</span></div><div className="grounding-column grounding-system"><div className="eyebrow text-success">System-verified projection</div><div className="mt-2 text-sm font-semibold text-main">Deterministic checks</div><div className="mt-1 text-xs leading-5 text-muted">Compiler, target validation, policy, and retrieval metadata remain separate from model output.</div><div className="mt-3 flex flex-wrap gap-2"><Badge tone={run.policy.length ? "success" : "neutral"}><ShieldCheck size={12} aria-hidden="true" /> {run.policy.length ? "policy recorded" : "policy not recorded"}</Badge><Badge tone={run.rag_documents.length ? "success" : "neutral"}><BookOpen size={12} aria-hidden="true" /> {run.rag_documents.length ? "evidence recorded" : "evidence unavailable"}</Badge></div></div></div>
    <div><SectionHeader eyebrow="Grounding stages" title="Evidence before authority" description="Stages are derived from the runtime’s bounded node projection." /><div className="grounding-stage-grid">{stages.map((stage) => <div className="grounding-stage-card" key={stage.id}><div className="flex items-start justify-between gap-2"><div className="flex items-center gap-2">{stage.status === "completed" ? <CheckCircle2 size={15} className="text-success" aria-hidden="true" /> : <CircleDot size={15} className="text-muted" aria-hidden="true" />}<span className="text-xs font-medium text-main">{stage.label}</span></div><Badge tone={stage.status === "completed" ? "success" : "neutral"}>{stage.status.replace(/_/g, " ")}</Badge></div><p className="mt-2 text-[11px] leading-5 text-muted">{stage.explanation}</p></div>)}</div></div>
    <div><SectionHeader eyebrow="RAG / knowledge" title="Retrieved evidence" description="Document metadata only; raw knowledge content remains outside the operator projection." /><RagPanel documents={run.rag_documents} grounding={run.answer_grounding} retrievalRecorded={run.trace.some((event) => event.stage === "context_retrieval")} embedded /></div>
    <div><SectionHeader eyebrow="Observed lifecycle" title="Grounding trace" description="Expand a stage to inspect its timestamp and duration when available." /><TraceStageTimeline run={run} compact /></div>
  </div>;
}
