import { Activity, BookOpen, Brain, GitBranch, ShieldCheck, Wrench } from "lucide-react";
import type { AgentRun } from "../types";
import { Badge, DataRow, EmptyState, MetricCard, Panel, SectionHeader, StatusIndicator, Tabs } from "./ui";
import { ToolPanel } from "./ToolPanel";
import { PolicyPanel } from "./PolicyPanel";
import { RagPanel } from "./RagPanel";
import { MemoryPanel } from "./MemoryPanel";
import { TraceTimeline } from "./TraceTimeline";

export function Inspector({ run, memoryRecords = [] }: { run: AgentRun | null; memoryRecords?: import("../types").MemoryRecord[] }) {
  if (!run) return <Panel title="Agent inspector" eyebrow="Run analysis"><EmptyState title="No run selected" description="Run an agent request to inspect intent, tools, policy, evidence, and trace data." icon={Activity} /></Panel>;
  const components = [run.memory.item_count > 0 && "Memory", run.rag_documents.length > 0 && "RAG", run.tools.length > 0 && "Tool", run.policy.length > 0 && "Policy"].filter(Boolean) as string[];
  const risk = run.tools.reduce((max, tool) => Math.max(max, tool.risk_level ?? 0), 0);
  const overview = <div className="space-y-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><MetricCard label="Intent" value={run.intent} icon={Activity} /><MetricCard label="Request type" value={run.request_type.replace(/_/g, " ")} icon={GitBranch} /><MetricCard label="Risk" value={`Level ${risk}`} icon={ShieldCheck} /><MetricCard label="Latency" value={`${run.duration_ms.toFixed(1)} ms`} icon={Activity} /></div><div className="grid gap-5 lg:grid-cols-2"><div><SectionHeader title="Run metadata" description="Safe identifiers for correlation." /><div className="divide-y divide-border/70"><DataRow label="Status" value={<StatusIndicator label={run.status} tone={run.status === "completed" ? "success" : run.status === "waiting_confirmation" ? "warning" : "danger"} compact />} /><DataRow label="Conversation" value={run.conversation_id} mono /><DataRow label="Agent run" value={run.run_id} mono /><DataRow label="Action" value={run.action_id ?? "none"} mono /><DataRow label="Trace" value={run.trace_id ?? "not exported"} mono /></div></div><div><SectionHeader title="Components used" description="Observed execution boundaries in this run." /><div className="flex flex-wrap gap-2">{components.length ? components.map((component) => <Badge key={component} tone="success"><span className="inline-flex items-center gap-1.5"><ShieldCheck size={12} aria-hidden="true" />{component}</span></Badge>) : <span className="text-xs text-muted">No downstream components recorded.</span>}</div></div></div><div><SectionHeader title="Execution path" description="Structured graph nodes only; no hidden reasoning." /><div className="path-strip">{run.path.map((step, index) => <span className="path-step" key={`${step}-${index}`}>{step}{index < run.path.length - 1 && <span className="path-arrow" aria-hidden="true">›</span>}</span>)}</div></div></div>;
  const tabs = [{ id: "overview", label: "Overview", icon: Activity, content: overview }, { id: "tools", label: "Tools", icon: Wrench, content: <ToolPanel tools={run.tools} embedded /> }, { id: "policy", label: "Policy", icon: ShieldCheck, content: <PolicyPanel events={run.policy} embedded /> }, { id: "rag", label: "RAG", icon: BookOpen, content: <RagPanel documents={run.rag_documents} embedded /> }, { id: "memory", label: "Memory", icon: Brain, content: <MemoryPanel usage={run.memory} records={memoryRecords} embedded /> }, { id: "trace", label: "Trace", icon: GitBranch, content: <TraceTimeline events={run.trace} embedded /> }];
  return <Panel title="Agent inspector" eyebrow="Run analysis" description="Structured metadata across the agent execution path."><Tabs tabs={tabs} /></Panel>;
}

export function Metric({ label, value }: { label: string; value: string }) { return <MetricCard label={label} value={value} />; }
export function Empty({ text }: { text: string }) { return <EmptyState title="Nothing to inspect" description={text} />; }
